export const testData = [
  {
    discord_link: 'discord.gg/project1',
    discord_users: 1000,
    floor: 5,
    ico: 'https://via.placeholder.com/150',
    id: 1,
    name: 'Project-1',
    ords_level_high: 10,
    ords_level_low: 0,
    supply: 2000,
    transfets: 100,
    twitter: '@project1',
    website: 'www.project1.com',
  },
  {
    discord_link: 'discord.gg/project1',
    discord_users: 1000,
    floor: 5,
    ico: 'https://via.placeholder.com/150',
    id: 2,
    name: 'Project-2',
    ords_level_high: 10,
    ords_level_low: 0,
    supply: 2000,
    transfets: 1000,
    twitter: '@project1',
    website: 'www.project1.com',
  },
  {
    discord_link: 'discord.gg/project1',
    discord_users: 1000,
    floor: 5,
    ico: 'https://via.placeholder.com/150',
    id: 3,
    name: 'Project-2',
    ords_level_high: 10,
    ords_level_low: 0,
    supply: 2000,
    transfets: 1000,
    twitter: '@project1',
    website: 'www.project1.com',
  },
];
